# Site settings
title: Intel TAP blogs
JIRA: https://trustedanalytics.atlassian.net
description: > # this means to ignore newlines until "baseurl:"
  Here you can find blog posts on  Trusted Analytics Platfrom usages, upgrades, issues and latest news on what is going on in the project.
baseurl: "/blogs" # the subpath of your site, e.g. /blog/
url: "https://trustedanalytics.github.io" # the base hostname & protocol for your site
twitter_username: trustedanalytic
github_username: "trustedanalytics"

# Build settings
markdown: kramdown
